from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "synopsis"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page=reverse_lazy("synopsis:login")),
        name="logout",
    ),
    path("project/new/", views.project_create, name="project_create"),
    path("project/<int:project_id>/", views.project_hub, name="project_hub"),
    path(
        "project/<int:project_id>/settings/",
        views.project_settings,
        name="project_settings",
    ),
    path(
        "project/<int:project_id>/phase/confirm/<str:phase>/",
        views.project_phase_confirm,
        name="project_phase_confirm",
    ),
    path(
        "project/<int:project_id>/team/",
        views.project_authors_manage,
        name="project_authors_manage",
    ),
    path(
        "project/<int:project_id>/action-list/",
        views.action_list_detail,
        name="action_list_detail",
    ),
    path(
        "project/<int:project_id>/action-list/delete-file/",
        views.action_list_delete_file,
        name="action_list_delete_file",
    ),
    path(
        "project/<int:project_id>/action-list/set-stage/",
        views.action_list_set_stage,
        name="action_list_set_stage",
    ),
    path(
        "project/<int:project_id>/action-list/revision/<int:revision_id>/restore/",
        views.action_list_restore_revision,
        name="action_list_restore_revision",
    ),
    path(
        "project/<int:project_id>/action-list/revision/<int:revision_id>/delete/",
        views.action_list_delete_revision,
        name="action_list_delete_revision",
    ),
    path(
        "project/<int:project_id>/action-list/clear-text/",
        views.action_list_clear_text,
        name="action_list_clear_text",
    ),
    path(
        "project/<int:project_id>/action-list/delete/",
        views.action_list_delete,
        name="action_list_delete",
    ),
    path(
        "project/<int:project_id>/protocol/",
        views.protocol_detail,
        name="protocol_detail",
    ),
    path(
        "project/<int:project_id>/protocol/delete-file/",
        views.protocol_delete_file,
        name="protocol_delete_file",
    ),
    path(
        "project/<int:project_id>/protocol/set-stage/",
        views.protocol_set_stage,
        name="protocol_set_stage",
    ),
    path(
        "project/<int:project_id>/protocol/revision/<int:revision_id>/restore/",
        views.protocol_restore_revision,
        name="protocol_restore_revision",
    ),
    path(
        "project/<int:project_id>/protocol/revision/<int:revision_id>/delete/",
        views.protocol_delete_revision,
        name="protocol_delete_revision",
    ),
    path(
        "project/<int:project_id>/protocol/clear-text/",
        views.protocol_clear_text,
        name="protocol_clear_text",
    ),
    path(
        "project/<int:project_id>/protocol/delete/",
        views.protocol_delete,
        name="protocol_delete",
    ),
    path(
        "project/<int:project_id>/<slug:document_slug>/collaborative/start/",
        views.collaborative_start,
        name="collaborative_start",
    ),
    path(
        "project/<int:project_id>/<slug:document_slug>/collaborative/<uuid:token>/",
        views.collaborative_edit,
        name="collaborative_edit",
    ),
    path(
        "project/<int:project_id>/<slug:document_slug>/collaborative/<uuid:token>/force-end/",
        views.collaborative_force_end,
        name="collaborative_force_end",
    ),
    path(
        "project/<int:project_id>/<slug:document_slug>/collaborative/<uuid:token>/callback/",
        views.collaborative_edit_callback,
        name="collaborative_edit_callback",
    ),
    path(
        "project/<int:project_id>/funders/add/",
        views.project_funder_add,
        name="project_funder_add",
    ),
    path(
        "project/<int:project_id>/funders/<int:funder_id>/edit/",
        views.project_funder_edit,
        name="project_funder_edit",
    ),
    path(
        "project/<int:project_id>/funders/<int:funder_id>/delete/",
        views.project_funder_delete,
        name="project_funder_delete",
    ),
    path(
        "project/<int:project_id>/delete/",
        views.project_delete,
        name="project_delete",
    ),
    path("manager/", views.manager_dashboard, name="manager_dashboard"),
    path("manager/users/new/", views.user_create, name="user_create"),
    path(
        "project/<int:project_id>/advisory-board/",
        views.advisory_board_list,
        name="advisory_board_list",
    ),
    path(
        "project/<int:project_id>/advisory-board/reminders/",
        views.advisory_schedule_reminders,
        name="advisory_schedule_reminders",
    ),
    path(
        "project/<int:project_id>/advisory-board/protocol-reminders/",
        views.advisory_schedule_protocol_reminders,
        name="advisory_schedule_protocol_reminders",
    ),
    path(
        "project/<int:project_id>/advisory-board/action-list-reminders/",
        views.advisory_schedule_action_list_reminders,
        name="advisory_schedule_action_list_reminders",
    ),
    path(
        "project/<int:project_id>/advisory-board/member/<int:member_id>/reminder/<str:kind>/",
        views.advisory_member_set_deadline,
        name="advisory_member_set_deadline",
    ),
    path(
        "project/<int:project_id>/advisory-board/member/<int:member_id>/edit/",
        views.advisory_member_edit,
        name="advisory_member_edit",
    ),
    path(
        "project/<int:project_id>/advisory-board/protocol-feedback/close/",
        views.advisory_protocol_feedback_close,
        name="advisory_protocol_feedback_close",
    ),
    path(
        "project/<int:project_id>/advisory-board/action-list-feedback/close/",
        views.advisory_action_list_feedback_close,
        name="advisory_action_list_feedback_close",
    ),
    path(
        "project/<int:project_id>/references/",
        views.reference_batch_list,
        name="reference_batch_list",
    ),
    path(
        "project/<int:project_id>/references/batch/<int:batch_id>/",
        views.reference_batch_detail,
        name="reference_batch_detail",
    ),
    path(
        "project/<int:project_id>/references/<int:reference_id>/delete/",
        views.reference_delete,
        name="reference_delete",
    ),
    path(
        "project/<int:project_id>/references/batch/<int:batch_id>/delete/",
        views.reference_batch_delete,
        name="reference_batch_delete",
    ),
    path(
        "project/<int:project_id>/references/upload/",
        views.reference_batch_upload,
        name="reference_batch_upload",
    ),
    path(
        "project/<int:project_id>/advisory-board/invite/",
        views.advisory_invite_create,
        name="advisory_invite_create",
    ),
    path(
        "project/<int:project_id>/advisory-board/member/<int:member_id>/invite/",
        views.advisory_invite_create,
        name="advisory_invite_create_for_member",
    ),
    path(
        "project/<int:project_id>/advisory-board/member/<int:member_id>/custom/",
        views.advisory_member_custom_data,
        name="advisory_member_custom_data",
    ),
    path(
        "advisory-board/invite/accept/<uuid:token>/",
        views.advisory_invite_accept,
        name="advisory_invite_accept",
    ),
    path(
        "advisory/invite/<uuid:token>/<str:choice>/",
        views.advisory_invite_reply,
        name="advisory_invite_reply",
    ),
    path(
        "project/<int:project_id>/advisory/send-invites/",
        views.send_advisory_invites,
        name="advisory_send_invites",
    ),
    path(
        "project/<int:project_id>/advisory/compose-invites/all/",
        views.advisory_send_invites_bulk,
        name="advisory_invite_compose_all",
    ),
    path(
        "project/<int:project_id>/advisory/send-invites/all/",
        views.advisory_send_invites_bulk,
        name="advisory_send_invites_bulk",
    ),
    path(
        "project/<int:project_id>/advisory/invite/<int:invitation_id>/due-date/",
        views.advisory_invite_update_due_date,
        name="advisory_invite_update_due_date",
    ),
    path(
        "project/<int:project_id>/advisory/send-protocol/all/",
        views.advisory_send_protocol_compose_all,
        name="advisory_send_protocol_compose_all",
    ),
    path(
        "project/<int:project_id>/advisory/send-protocol/member/<int:member_id>/",
        views.advisory_send_protocol_compose_member,
        name="advisory_send_protocol_compose_member",
    ),
    path(
        "project/<int:project_id>/advisory/send-action-list/all/",
        views.advisory_send_action_list_compose_all,
        name="advisory_send_action_list_compose_all",
    ),
    path(
        "project/<int:project_id>/advisory/send-action-list/member/<int:member_id>/",
        views.advisory_send_action_list_compose_member,
        name="advisory_send_action_list_compose_member",
    ),
    path(
        "advisory/protocol/feedback/<uuid:token>/",
        views.protocol_feedback,
        name="protocol_feedback",
    ),
    path(
        "advisory/action-list/feedback/<uuid:token>/",
        views.action_list_feedback,
        name="action_list_feedback",
    ),
    path(
        "project/<int:project_id>/advisory/send-invite/member/<int:member_id>/",
        views.advisory_send_invite_member,
        name="advisory_send_invite_member",
    ),
]
