# Generated by Django 5.2.6 on 2025-11-09 22:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis_wagtail", "0003_extend_chapter_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synopsischapterpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 2),
                    ("reference_summary", 4),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "label": "Heading"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h3", "bold", "italic", "ol", "ul", "link"],
                            "label": "Paragraph",
                        },
                    ),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("synopsis.ReferenceSummary",),
                        {"label": "Summary"},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("summary", 3)]], {}),
                },
            ),
        ),
    ]
