# Generated by Django 5.2.6 on 2025-11-10 13:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis_wagtail", "0004_alter_synopsischapterpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synopsischapterpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("quote", 2),
                    ("reference_summary", 7),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "label": "Heading"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h3", "bold", "italic", "ol", "ul", "link"],
                            "label": "Paragraph",
                        },
                    ),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("synopsis.ReferenceSummary",),
                        {"label": "Summary"},
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "(auto) action summary identifier",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("summary", 3),
                                ("action_summary_id", 4),
                                ("action_summary_name", 5),
                                ("action_summary_text", 6),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
