name: Auto-label Issues
on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label based on issue content
        uses: actions/github-script@v6
        with:
          script: |
            const body = (context.payload.issue && context.payload.issue.body) || '';
            const title = (context.payload.issue && context.payload.issue.title) || '';
            const labels = [];

            // Bug indicators
            if (
              body.includes('Steps to Reproduce') ||
              /bug|error|crash/i.test(title) ||
              /error|crash/i.test(body)
            ) labels.push('bug');

            // Feature / enhancement
            if (/feature|enhancement/i.test(title) || /new feature/i.test(body)) {
              labels.push('enhancement');
            }

            // Documentation
            if (/documentation|docs/i.test(title) || /documentation/i.test(body)) {
              labels.push('documentation');
            }

            // Browser-specific labels
            if (/Chrome/.test(body)) labels.push('browser:chrome');
            if (/Safari/.test(body)) labels.push('browser:safari');
            if (/Firefox/.test(body)) labels.push('browser:firefox');
            if (/Edge/.test(body)) labels.push('browser:edge');

            // OS-specific labels
            if (/Windows/.test(body)) labels.push('os:windows');
            if (/macOS|Mac/.test(body)) labels.push('os:macos');
            if (/Linux|Ubuntu/.test(body)) labels.push('os:linux');

            // Priority
            if (/critical|urgent/i.test(body) || /critical/i.test(title)) {
              labels.push('priority:high');
            }

            // Always add needs-triage
            labels.push('needs-triage');

            if (labels.length) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels
              });
            }