# Generated by Django 5.2.6 on 2025-09-11 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funder",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="start_date",
        ),
        migrations.AddField(
            model_name="funder",
            name="fund_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="fund_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("author", "Author"),
                            ("advisory_board", "Advisory Board Member"),
                            ("external_collaborator", "External Collaborator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="synopsis.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project", "role")},
            },
        ),
    ]
