# Generated by Django 5.2.6 on 2025-09-11 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0002_remove_funder_end_date_remove_funder_start_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryBoardInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="synopsis.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvisoryBoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("organisation", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("continent", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("invite_sent", models.BooleanField(default=False)),
                ("response_date", models.DateField(blank=True, null=True)),
                ("response", models.CharField(blank=True, max_length=100)),
                ("feedback_on_list", models.BooleanField(default=False)),
                ("feedback_on_actions_received", models.BooleanField(default=False)),
                ("wm_replied", models.BooleanField(default=False)),
                ("feedback_added_to_action_list", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("sent_protocol", models.BooleanField(default=False)),
                (
                    "feedback_on_protocol_deadline",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_on_protocol_received",
                    models.DateField(blank=True, null=True),
                ),
                ("added_to_protocol_doc", models.BooleanField(default=False)),
                ("feedback_on_guidance", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisory_board_members",
                        to="synopsis.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="protocols/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("text_version", models.TextField(blank=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol",
                        to="synopsis.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VocabularyTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("action", "Action / Intervention"),
                            ("threat", "Threat"),
                            ("taxon", "Taxon"),
                            ("species", "Species"),
                            ("habitat", "Habitat"),
                            ("location", "Location"),
                            ("design", "Research design"),
                            ("keyword", "Keyword"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="synopsis.vocabularyterm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["type", "label"], name="synopsis_vo_type_2d1a54_idx"
                    )
                ],
            },
        ),
    ]
