# Generated by Django 5.2.6 on 2025-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "synopsis",
            "0003_advisoryboardinvitation_advisoryboardmember_protocol_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="invite_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
