# Generated by Django 5.2.6 on 2025-09-13 19:10

from django.db import migrations, models


def backfill_invite_sent(apps, schema_editor):
    Member = apps.get_model("synopsis", "AdvisoryBoardMember")
    Member.objects.filter(invite_sent_at__isnull=False).update(invite_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        (
            "synopsis",
            "0004_advisoryboardmember_invite_sent_at",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="advisoryboardmember",
                    name="invite_sent",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE synopsis_advisoryboardmember "
                        "ADD COLUMN IF NOT EXISTS invite_sent BOOLEAN "
                        "NOT NULL DEFAULT FALSE"
                    ),
                    reverse_sql=(
                        "ALTER TABLE synopsis_advisoryboardmember "
                        "DROP COLUMN IF EXISTS invite_sent"
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_invite_sent, migrations.RunPython.noop),
    ]
