# Generated by Django 5.2.6 on 2025-09-13 19:10

from django.db import migrations, models


def backfill_reminder_sent(apps, schema_editor):
    Member = apps.get_model("synopsis", "AdvisoryBoardMember")
    Member.objects.filter(reminder_sent_at__isnull=False).update(reminder_sent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("synopsis", "0005_add_invite_sent_boolean"),
    ]

    operations = [
        # Make sure the column exists in DB but don't error if it already does,
        # and also update Django's *state* so it knows about the field.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE synopsis_advisoryboardmember
                    ADD COLUMN IF NOT EXISTS reminder_sent_at timestamp with time zone NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE synopsis_advisoryboardmember
                    DROP COLUMN IF EXISTS reminder_sent_at;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="advisoryboardmember",
                    name="reminder_sent_at",
                    field=models.DateTimeField(null=True, blank=True),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="advisoryboardmember",
                    name="reminder_sent",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE synopsis_advisoryboardmember "
                        "ADD COLUMN IF NOT EXISTS reminder_sent BOOLEAN "
                        "NOT NULL DEFAULT FALSE"
                    ),
                    reverse_sql=(
                        "ALTER TABLE synopsis_advisoryboardmember "
                        "DROP COLUMN IF EXISTS reminder_sent"
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_reminder_sent, migrations.RunPython.noop),
    ]
