# Generated by Django 5.2.6 on 2025-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("synopsis", "0007_add_sent_protocol_boolean"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE synopsis_advisoryboardmember DROP COLUMN IF EXISTS alt_emails;",
                    reverse_sql="ALTER TABLE synopsis_advisoryboardmember ADD COLUMN alt_emails text NOT NULL DEFAULT '';",
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE synopsis_advisoryboardmember
                        ADD COLUMN IF NOT EXISTS sent_protocol_at timestamp with time zone NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE synopsis_advisoryboardmember
                        DROP COLUMN IF EXISTS sent_protocol_at;
                    """,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE synopsis_advisoryboardmember DROP COLUMN IF EXISTS sent_protocol;",
                    reverse_sql="ALTER TABLE synopsis_advisoryboardmember ADD COLUMN sent_protocol boolean NOT NULL DEFAULT false;",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="advisoryboardmember",
                    name="sent_protocol",
                ),
                migrations.AddField(
                    model_name="advisoryboardmember",
                    name="sent_protocol_at",
                    field=models.DateTimeField(null=True, blank=True),
                ),
            ],
        ),
    ]
