# Generated by Django 5.2.6 on 2025-09-13 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "synopsis",
            "0008_schema_cleanup",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE synopsis_advisoryboardmember DROP COLUMN IF EXISTS invite_method;",
            reverse_sql="ALTER TABLE synopsis_advisoryboardmember ADD COLUMN invite_method text NOT NULL DEFAULT 'email';",
        ),
    ]
