# Generated by Django 5.2.6 on 2025-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0009_drop_invite_method_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
