# Generated by Django 5.2.6 on 2025-09-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0010_advisoryboardmember_middle_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE synopsis_advisoryboardmember
                      DROP COLUMN IF EXISTS website,
                      DROP COLUMN IF EXISTS invite_method,
                      DROP COLUMN IF EXISTS alt_emails,
                      DROP COLUMN IF EXISTS sent_protocol;
                    """
                ),
            ],
            state_operations=[],
        ),
    ]
