# Generated by Django 5.2.6 on 2025-09-13 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0011_db_cleanup_abm_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardinvitation",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="synopsis.advisoryboardmember",
            ),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="accepted",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryboardinvitation",
            index=models.Index(
                fields=["project", "email"], name="synopsis_ad_project_7e64cb_idx"
            ),
        ),
    ]
