# Generated by Django 5.2.6 on 2025-09-13 21:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0012_advisoryboardinvitation_member_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="advisoryboardinvitation",
            name="synopsis_ad_project_7e64cb_idx",
        ),
        migrations.AddField(
            model_name="advisoryboardinvitation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="advisoryboardinvitation",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryboardinvitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
