# Generated by Django 5.2.6 on 2025-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "synopsis",
            "0013_remove_advisoryboardinvitation_synopsis_ad_project_7e64cb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="contact_first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="funder",
            name="contact_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="funder",
            name="organisation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="funder",
            name="funds_allocated",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
