# Generated by Django 5.2.6 on 2025-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0014_extend_funder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="stage",
            field=models.CharField(
                choices=[("draft", "Draft"), ("final", "Final")],
                default="draft",
                max_length=20,
            ),
        ),
    ]

