# Generated by Django 5.2.6 on 2025-09-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0015_protocol_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="phase_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft_protocol", "Draft protocol"),
                    ("invite_advisory_board", "Invite advisory board"),
                    ("references_screening", "References screening"),
                    ("summary_writing", "Summary writing"),
                    ("draft_chapters", "Draft chapters"),
                    ("draft_synopsis", "Draft synopsis"),
                    ("final_review", "Final review"),
                    ("publication", "Publication"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase_manual_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProjectPhaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("draft_protocol", "Draft protocol"),
                            ("invite_advisory_board", "Invite advisory board"),
                            ("references_screening", "References screening"),
                            ("summary_writing", "Summary writing"),
                            ("draft_chapters", "Draft chapters"),
                            ("draft_synopsis", "Draft synopsis"),
                            ("final_review", "Final review"),
                            ("publication", "Publication"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_events",
                        to="synopsis.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-confirmed_at", "-id"],
            },
        ),
    ]
