# Generated by Django 5.2.6 on 2025-09-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0016_project_phase_manual_and_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("token", models.UUIDField(editable=False, unique=True)),
                ("content", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_feedback",
                        to="synopsis.advisoryboardinvitation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_feedback",
                        to="synopsis.advisoryboardmember",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_feedback",
                        to="synopsis.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
    ]
