# Generated by Django 5.2.6 on 2025-09-16 12:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0017_protocolfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolfeedback",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="protocolfeedback",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
