# Generated by Django 4.2.5 on 2024-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0019_projectchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="protocol_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="protocol_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
