# Generated by Django 5.2.6 on 2025-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0020_advisoryboardmember_protocol_reminder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="participation_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="participation_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="participation_statement",
            field=models.TextField(blank=True),
        ),
    ]
