# Generated by Django 5.2.6 on 2025-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0021_advisoryboardmember_participation_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="feedback_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocol",
            name="feedback_closure_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="protocolfeedback",
            name="feedback_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisoryboardmember",
            name="feedback_on_protocol_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            """
            UPDATE synopsis_advisoryboardmember
            SET feedback_on_protocol_deadline = feedback_on_protocol_deadline + INTERVAL '23 hours 59 minutes'
            WHERE feedback_on_protocol_deadline IS NOT NULL
              AND EXTRACT(HOUR FROM feedback_on_protocol_deadline) = 0
              AND EXTRACT(MINUTE FROM feedback_on_protocol_deadline) = 0
              AND EXTRACT(SECOND FROM feedback_on_protocol_deadline) = 0
            """,
            reverse_sql="""
            UPDATE synopsis_advisoryboardmember
            SET feedback_on_protocol_deadline = DATE_TRUNC('day', feedback_on_protocol_deadline)
            WHERE feedback_on_protocol_deadline IS NOT NULL
            """,
        ),
    ]
