# Generated by Django 5.2.6 on 2025-09-18 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0022_protocol_feedback_closed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceSourceBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short identifier shown to authors (e.g. 'Scopus Jan 2023').",
                        max_length=255,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("journal_search", "Journal / database search"),
                            ("grey_literature", "Grey literature search"),
                            ("non_english", "Non-English search"),
                            ("manual_upload", "Manual upload"),
                            ("legacy", "Legacy import"),
                        ],
                        max_length=40,
                    ),
                ),
                ("search_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("record_count", models.PositiveIntegerField(default=0)),
                (
                    "ris_sha1",
                    models.CharField(
                        blank=True,
                        help_text="SHA1 fingerprint of the original RIS payload for deduplication.",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_batches",
                        to="synopsis.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_reference_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reference batch",
                "verbose_name_plural": "reference batches",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hash_key",
                    models.CharField(
                        db_index=True,
                        help_text="HASH used to detect duplicates within a project.",
                        max_length=40,
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identifier from the source RIS (e.g. RefID or Accession number).",
                        max_length=255,
                    ),
                ),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                ("authors", models.TextField(blank=True)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("journal", models.CharField(blank=True, max_length=255)),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("issue", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("language", models.CharField(blank=True, max_length=50)),
                (
                    "raw_ris",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original RIS key/value pairs for full fidelity storage.",
                    ),
                ),
                (
                    "screening_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending triage"),
                            ("title_included", "Title/abstract included"),
                            ("title_excluded", "Title/abstract excluded"),
                            ("needs_full_text", "Needs full text"),
                            ("fulltext_included", "Full text included"),
                            ("fulltext_excluded", "Full text excluded"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("screening_notes", models.TextField(blank=True)),
                ("screening_decision_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="synopsis.project",
                    ),
                ),
                (
                    "screened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screened_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="synopsis.referencesourcebatch",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("project", "hash_key")},
            },
        ),
    ]
