# Generated by Django 5.2.6 on 2025-09-22 10:07

import os
import django.db.models.deletion
import synopsis.models
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import migrations, models


def seed_initial_protocol_revisions(apps, schema_editor):
    Protocol = apps.get_model("synopsis", "Protocol")
    ProtocolRevision = apps.get_model("synopsis", "ProtocolRevision")

    for proto in Protocol.objects.all():
        document = getattr(proto, "document", None)
        if not document:
            continue
        try:
            with document.open("rb") as source:
                content = source.read()
        except FileNotFoundError:
            continue
        if not content:
            continue
        filename = os.path.basename(document.name)
        revision = ProtocolRevision(
            protocol=proto,
            stage=proto.stage or "draft",
            change_reason="Initial upload",
        )
        revision.original_name = filename
        revision.file_size = len(content)
        revision.file.save(filename, ContentFile(content), save=True)
        proto.current_revision = revision
        proto.save(update_fields=["current_revision"])


def unseed_initial_protocol_revisions(apps, schema_editor):
    Protocol = apps.get_model("synopsis", "Protocol")
    ProtocolRevision = apps.get_model("synopsis", "ProtocolRevision")
    ProtocolRevision.objects.all().delete()
    Protocol.objects.update(current_revision=None)


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0023_referencesourcebatch_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=synopsis.models.protocol_revision_upload_path
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")], max_length=20
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="synopsis.protocol",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="protocol",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for",
                to="synopsis.protocolrevision",
            ),
        ),
        migrations.RunPython(
            seed_initial_protocol_revisions, unseed_initial_protocol_revisions
        ),
    ]
