# Generated by Django 5.2.6 on 2025-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0025_protocolrevision_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="contact_title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
