# Generated by Django 5.2.6 on 2025-09-28 17:49

import django.db.models.deletion
import synopsis.models
import uuid
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0027_project_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to=synopsis.models.action_list_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("text_version", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("feedback_closed_at", models.DateTimeField(blank=True, null=True)),
                ("feedback_closure_message", models.TextField(blank=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_list",
                        to="synopsis.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action list",
                "verbose_name_plural": "Action lists",
            },
        ),
        migrations.CreateModel(
            name="ActionListRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=synopsis.models.action_list_revision_upload_path
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")], max_length=20
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "action_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="synopsis.actionlist",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_list_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActionListFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "uploaded_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="action_list_feedback_uploads/",
                    ),
                ),
                (
                    "action_list_document_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "action_list_document_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "action_list_stage_snapshot",
                    models.CharField(blank=True, max_length=20),
                ),
                ("feedback_deadline_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="synopsis.actionlist",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_list_feedback",
                        to="synopsis.advisoryboardinvitation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_list_feedback",
                        to="synopsis.advisoryboardmember",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_list_feedback",
                        to="synopsis.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="actionlist",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for",
                to="synopsis.actionlistrevision",
            ),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="action_list_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="action_list_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="added_to_action_list_doc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="feedback_on_action_list_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="feedback_on_action_list_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="sent_action_list_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
