# Generated by Django 5.2.6 on 2025-09-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0028_actionlist_actionlistrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="title",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
