# Generated by Django 5.2.6 on 2025-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0031_collaborativesession_patch"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborativesession",
            name="invitations",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborative_sessions",
                to="synopsis.advisoryboardinvitation",
            ),
        ),
    ]
