# Generated by Django 5.2.6 on 2025-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0032_collaborativesession_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborativesession",
            name="last_participant_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
