# Generated by Django 5.2.6 on 2025-10-13 16:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0033_collaborativesession_last_participant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryBoardCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Yes / No"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "sections",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("accepted", "Accepted"),
                                ("pending", "Pending"),
                                ("declined", "Declined"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Leave blank to display in every section.",
                        size=None,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisory_custom_fields",
                        to="synopsis.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryBoardCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="synopsis.advisoryboardcustomfield",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="synopsis.advisoryboardmember",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="advisoryboardcustomfield",
            constraint=models.UniqueConstraint(
                fields=("project", "slug"), name="unique_custom_field_slug"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="advisoryboardcustomfieldvalue",
            unique_together={("field", "member")},
        ),
    ]
