# Generated by Django 5.2.6 on 2025-10-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0036_advisoryboardcustomfieldvaluehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryboardmember",
            name="added_to_synopsis_doc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="feedback_on_synopsis_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="feedback_on_synopsis_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="sent_synopsis_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="synopsis_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisoryboardmember",
            name="synopsis_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
