# Generated by Django 5.2.6 on 2025-11-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0042_referencesourcebatchnotehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="screening_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("included", "Include"),
                    ("excluded", "Exclude"),
                ],
                default="pending",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ReferenceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To summarise"),
                            ("draft", "In progress"),
                            ("review", "Ready for review"),
                            ("done", "Synopsised"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("needs_help", models.BooleanField(default=False)),
                ("summary_text", models.TextField(blank=True)),
                ("key_findings", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_summary_model", models.CharField(blank=True, max_length=255)),
                (
                    "ai_summary_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("action_tags", models.JSONField(blank=True, default=list)),
                ("threat_tags", models.JSONField(blank=True, default=list)),
                ("taxon_tags", models.JSONField(blank=True, default=list)),
                ("habitat_tags", models.JSONField(blank=True, default=list)),
                ("location_tags", models.JSONField(blank=True, default=list)),
                ("research_design", models.CharField(blank=True, max_length=255)),
                ("citation", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_summaries",
                        to="synopsis.project",
                    ),
                ),
                (
                    "reference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="synopsis.reference",
                    ),
                ),
            ],
            options={
                "ordering": ["reference__title"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceSummaryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="synopsis.referencesummary",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
