# Generated by Django 5.2.6 on 2025-11-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0042_referencesourcebatchnotehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlistrevision",
            name="version_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="protocolrevision",
            name="version_label",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
