# Generated by Django 5.2.6 on 2025-11-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0049_outline_chapter_section_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synopsisoutlinechapter",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("front_matter", "Front matter"),
                    ("threat", "Threat"),
                    ("action", "Action group"),
                    ("appendix", "Appendix"),
                ],
                default="front_matter",
                max_length=20,
            ),
        ),
    ]
