# Generated by Django 5.2.6 on 2025-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0052_set_front_matter_template_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencesummary",
            name="action_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="action_methods",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="experimental_design",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="habitat_and_sites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="reference_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="reference_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="region",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="sampling_methods_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="site_context_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="study_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="summary_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="summary_of_results",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="year_range",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
