# Generated by Django 5.2.6 on 2025-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0054_alter_synopsisoutlinechapter_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencesummary",
            name="benefits_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="harms_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="outcome_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="relevance_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="reliability_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
