# Generated by Django 5.2.6 on 2025-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0055_referencesummary_outcomes_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencesummary",
            name="cost_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="sites_replications",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="referencesummary",
            name="study_design",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
