# Generated by Django 5.2.6 on 2025-12-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0056_referencesummary_design_sites_costs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencesummary",
            name="cost_summary",
        ),
        migrations.RemoveField(
            model_name="referencesummary",
            name="sites_replications",
        ),
        migrations.RemoveField(
            model_name="referencesummary",
            name="study_design",
        ),
    ]
