# Generated by Django 5.2.6 on 2026-01-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0058_referencesummary_restore_design_sites_costs"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database: drop the column if it exists, but don't assume it is present in state.
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE synopsis_synopsisoutlinechapter DROP COLUMN IF EXISTS wagtail_page_id;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[],
        )
    ]
