# Generated by Django 5.2.6 on 2026-01-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0059_remove_synopsisoutlinechapter_wagtail_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencesummary",
            name="synopsis_draft",
            field=models.TextField(blank=True),
        ),
    ]
