# Generated by Django 5.2.6 on 2026-01-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0060_alter_referencesummary_synopsis_draft"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS synopsis_synopsisoutlineblock CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS synopsis_synopsisoutlinesection CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS synopsis_synopsisoutlinechapter CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name="SynopsisOutlineBlock"),
                migrations.DeleteModel(name="SynopsisOutlineSection"),
                migrations.DeleteModel(name="SynopsisOutlineChapter"),
            ],
        ),
        migrations.CreateModel(
            name="SynopsisChapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="synopsis_chapters", to="synopsis.project")),
            ],
            options={"ordering": ["position", "id"],},
        ),
        migrations.CreateModel(
            name="SynopsisSubheading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chapter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subheadings", to="synopsis.synopsischapter")),
            ],
            options={"ordering": ["position", "id"],},
        ),
        migrations.CreateModel(
            name="SynopsisIntervention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subheading", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interventions", to="synopsis.synopsissubheading")),
            ],
            options={"ordering": ["position", "id"],},
        ),
        migrations.CreateModel(
            name="SynopsisAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("intervention", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="synopsis.synopsisintervention")),
                ("reference_summary", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="synopsis_assignments", to="synopsis.referencesummary")),
            ],
            options={"ordering": ["position", "id"],},
        ),
        migrations.CreateModel(
            name="SynopsisExportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                ("archived_file", models.FileField(blank=True, upload_to="synopsis_exports/")),
                ("exported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="auth.user")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="synopsis_exports", to="synopsis.project")),
            ],
            options={"ordering": ["-exported_at", "id"],},
        ),
        migrations.AlterUniqueTogether(
            name="synopsisassignment",
            unique_together={("intervention", "reference_summary")},
        ),
    ]
