# Generated by Django 5.2.6 on 2026-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0067_reference_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencesummary",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To summarise"),
                    ("draft", "In progress"),
                    ("review", "Needs review/help"),
                    ("done", "Summarised"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
