# Generated by Django 5.2.6 on 2026-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0076_library_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='raw_ris',
            field=models.JSONField(blank=True, default=dict, help_text='Original import key/value pairs for full fidelity storage.'),
        ),
        migrations.AlterField(
            model_name='referencesourcebatch',
            name='source_type',
            field=models.CharField(choices=[('journal_search', 'Journal / database search'), ('grey_literature', 'Grey literature search'), ('non_english', 'Non-English search'), ('manual_upload', 'Manual upload'), ('library_link', 'Library link'), ('legacy', 'Legacy import')], max_length=40),
        ),
    ]
