# Generated by Django 5.2.6 on 2026-02-09 15:48

import django.db.models.deletion
from django.db import migrations, models


def seed_iucn_categories(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")
    seed_rows = [
        ("threat", "1", "Residential & commercial development", 10),
        ("threat", "2", "Agriculture & aquaculture", 20),
        ("threat", "3", "Energy production & mining", 30),
        ("threat", "4", "Transportation & service corridors", 40),
        ("threat", "5", "Biological resource use", 50),
        ("threat", "6", "Human intrusions & disturbance", 60),
        ("threat", "7", "Natural system modifications", 70),
        ("threat", "8", "Invasive/problematic species, genes & diseases", 80),
        ("threat", "9", "Pollution", 90),
        ("threat", "11", "Climate change & severe weather", 110),
        ("action", "1", "Land/water protection", 10),
        ("action", "2", "Land/water management", 20),
        ("action", "3", "Species management", 30),
        ("action", "4", "Education & awareness", 40),
        ("action", "5", "Law & policy", 50),
        ("action", "6", "Livelihood/economic incentives", 60),
        ("action", "7", "External capacity building", 70),
    ]
    for kind, code, name, position in seed_rows:
        IUCNCategory.objects.update_or_create(
            kind=kind,
            code=code,
            defaults={"name": name, "position": position, "is_active": True},
        )


def unseed_iucn_categories(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")
    IUCNCategory.objects.filter(
        kind__in=["threat", "action"],
        code__in=["1", "2", "3", "4", "5", "6", "7", "8", "9", "11"],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0078_repair_library_reference_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='synopsisintervention',
            name='is_cross_reference',
            field=models.BooleanField(default=False, help_text='Mark when evidence is summarized under another intervention and only referenced here.'),
        ),
        migrations.AddField(
            model_name='synopsisintervention',
            name='primary_intervention',
            field=models.ForeignKey(blank=True, help_text='Main intervention that contains the full evidence summary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_references', to='synopsis.synopsisintervention'),
        ),
        migrations.CreateModel(
            name='IUCNCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('threat', 'Direct threat'), ('action', 'Conservation action')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['kind', 'position', 'name'],
                'unique_together': {('kind', 'name')},
            },
        ),
        migrations.AddField(
            model_name='synopsisintervention',
            name='iucn_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='synopsis.iucncategory'),
        ),
        migrations.RunPython(seed_iucn_categories, unseed_iucn_categories),
    ]
