# Generated by Django 5.2.6 on 2026-02-10 10:58

from django.db import migrations, models


def classify_existing_chapters(apps, schema_editor):
    SynopsisChapter = apps.get_model("synopsis", "SynopsisChapter")
    SynopsisSubheading = apps.get_model("synopsis", "SynopsisSubheading")
    SynopsisIntervention = apps.get_model("synopsis", "SynopsisIntervention")
    text_titles = {
        "advisory board",
        "about the authors",
        "acknowledgements",
        "acknowledgments",
    }
    appendix_titles = {"references", "index"}

    for chapter in SynopsisChapter.objects.all():
        title = (chapter.title or "").strip().lower()
        chapter_type = None
        if title in text_titles or "about this book" in title:
            chapter_type = "text"
        elif title.startswith("appendix") or title in appendix_titles:
            chapter_type = "appendix"
        if not chapter_type:
            continue

        subheading_ids = list(
            SynopsisSubheading.objects.filter(chapter=chapter).values_list(
                "id", flat=True
            )
        )
        has_interventions = SynopsisIntervention.objects.filter(
            subheading_id__in=subheading_ids
        ).exists()
        if has_interventions:
            # Keep as evidence chapter if real intervention data already exists.
            continue

        if subheading_ids:
            SynopsisSubheading.objects.filter(id__in=subheading_ids).delete()

        if chapter.chapter_type != chapter_type:
            chapter.chapter_type = chapter_type
            chapter.save(update_fields=["chapter_type"])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0079_synopsisintervention_is_cross_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synopsischapter',
            name='chapter_type',
            field=models.CharField(choices=[('text', 'Text chapter'), ('evidence', 'Evidence chapter'), ('appendix', 'Appendix / back matter')], default='evidence', max_length=20),
        ),
        migrations.RunPython(classify_existing_chapters, noop),
    ]
