# Generated by Django 5.2.6 on 2026-02-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0080_synopsischapter_chapter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='synopsisintervention',
            name='ce_action_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='synopsisintervention',
            name='evidence_status',
            field=models.CharField(choices=[('has_evidence', 'Has evidence'), ('no_studies', 'No studies found')], default='has_evidence', max_length=20),
        ),
        migrations.AddField(
            model_name='synopsisintervention',
            name='synthesis_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SynopsisInterventionKeyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_group', models.CharField(choices=[('community', 'Community response'), ('population', 'Population response'), ('behaviour', 'Behaviour'), ('response', 'General response')], default='response', max_length=20)),
                ('outcome_label', models.CharField(blank=True, max_length=255)),
                ('statement', models.TextField()),
                ('study_count', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_messages', to='synopsis.synopsisintervention')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
