# Generated by Codex on 2026-03-24

from django.db import migrations


DETAILED_ACTION_ROWS = [
    ("1.1", "Land/water protection-Area protection", 10),
    ("1.2", "Land/water protection-Site/area stewardship", 20),
    ("2.1", "Land/water management-Site/area management", 30),
    ("2.2", "Land/water management-Invasive/problematic species control", 40),
    ("2.3", "Land/water management-Habitat & natural process restoration", 50),
    ("2.4", "Land/water management-Natural process regeneration", 60),
    ("3.1", "Species management-Species recovery", 70),
    ("3.2", "Species management-Species re-introduction", 80),
    ("3.3", "Species management-Ex situ conservation", 90),
    ("3.4", "Species management-Conservation translocation", 100),
    ("3.5", "Species management-Disease/pathogen treatment", 110),
    ("3.6", "Species management-Biological resource use management", 120),
    ("4.1", "Education & awareness-Formal education", 130),
    ("4.2", "Education & awareness-Training", 140),
    ("4.3", "Education & awareness-Awareness & communications", 150),
    ("5.1", "Law & policy-Legislation", 160),
    ("5.2", "Law & policy-Regulations", 170),
    ("5.3", "Law & policy-Incentives", 180),
    ("5.4", "Law & policy-Private sector standards & codes", 190),
    ("5.5", "Law & policy-Policies & regulations", 200),
    ("5.6", "Law & policy-Law enforcement & prosecution", 210),
    (
        "6.1",
        "Livelihood, economic & other incentives-Linked enterprises & livelihood alternatives",
        220,
    ),
    ("6.2", "Livelihood, economic & other incentives-Incentives/subsidies", 230),
    ("6.3", "Livelihood, economic & other incentives-Market forces", 240),
    ("6.4", "Livelihood, economic & other incentives-Conservation payments", 250),
    ("6.5", "Livelihood, economic & other incentives-Non-monetary values", 260),
    ("7.1", "External capacity building-Institutional development", 270),
    ("7.2", "External capacity building-Alliance & partnership development", 280),
    ("7.3", "External capacity building-Conservation finance", 290),
    ("7.4", "External capacity building-Capacity building", 300),
    ("7.5", "External capacity building-Technology transfer", 310),
    ("8.1", "Research & monitoring-Basic research & status monitoring", 320),
    ("8.2", "Research & monitoring-Resource & habitat management", 330),
    ("8.3", "Research & monitoring-Species management", 340),
    ("8.4", "Research & monitoring-Socio-economics", 350),
    ("8.5", "Research & monitoring-Conservation planning", 360),
    ("8.6", "Research & monitoring-Other", 370),
]

BROAD_ACTION_ROWS = [
    ("1", "Land/water protection", 10),
    ("2", "Land/water management", 20),
    ("3", "Species management", 30),
    ("4", "Education & awareness", 40),
    ("5", "Law & policy", 50),
    ("6", "Livelihood/economic incentives", 60),
    ("7", "External capacity building", 70),
]


def forwards(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")

    for code, name, position in DETAILED_ACTION_ROWS:
        IUCNCategory.objects.update_or_create(
            kind="action",
            name=name,
            defaults={
                "code": code,
                "position": position,
                "is_active": True,
            },
        )

    for code, name, position in BROAD_ACTION_ROWS:
        IUCNCategory.objects.update_or_create(
            kind="action",
            name=name,
            defaults={
                "code": code,
                "position": position,
                "is_active": False,
            },
        )


def backwards(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")

    IUCNCategory.objects.filter(
        kind="action",
        name__in=[name for _code, name, _position in DETAILED_ACTION_ROWS],
    ).update(is_active=False)

    for code, name, position in BROAD_ACTION_ROWS:
        IUCNCategory.objects.update_or_create(
            kind="action",
            name=name,
            defaults={
                "code": code,
                "position": position,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0087_project_advisory_invitation_message"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
