# Generated by Django 5.2.6 on 2026-04-24 20:44

import django.db.models.deletion
import django.utils.timezone
import synopsis.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0091_alter_protocol_document_upload_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryboardmember',
            name='added_to_guidance_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisoryboardmember',
            name='feedback_on_guidance_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisoryboardmember',
            name='feedback_on_guidance_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisoryboardmember',
            name='guidance_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisoryboardmember',
            name='guidance_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisoryboardmember',
            name='sent_guidance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborativesession',
            name='document_type',
            field=models.CharField(choices=[('protocol', 'Protocol'), ('action_list', 'Action list'), ('guidance', 'Guidance')], max_length=20),
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=synopsis.models.guidance_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('text_version', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('feedback_closed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_closure_message', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance', to='synopsis.project')),
            ],
            options={
                'verbose_name': 'Guidance',
                'verbose_name_plural': 'Guidance',
            },
        ),
        migrations.CreateModel(
            name='GuidanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='guidance_feedback_uploads/')),
                ('guidance_document_name', models.CharField(blank=True, max_length=255)),
                ('guidance_document_last_updated', models.DateTimeField(blank=True, null=True)),
                ('guidance_stage_snapshot', models.CharField(blank=True, max_length=20)),
                ('feedback_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('guidance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='synopsis.guidance')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_feedback', to='synopsis.advisoryboardinvitation')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_feedback', to='synopsis.advisoryboardmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_feedback', to='synopsis.project')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=synopsis.models.guidance_revision_upload_path)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('version_label', models.CharField(blank=True, max_length=120)),
                ('guidance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='synopsis.guidance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='guidance',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='synopsis.guidancerevision'),
        ),
        migrations.AddField(
            model_name='collaborativesession',
            name='initial_guidance_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_sessions_started_guidance', to='synopsis.guidancerevision'),
        ),
        migrations.AddField(
            model_name='collaborativesession',
            name='result_guidance_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_sessions_completed_guidance', to='synopsis.guidancerevision'),
        ),
    ]
