# Generated by Django 5.2.6 on 2026-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0092_advisoryboardmember_added_to_guidance_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryboardcustomfield',
            name='display_group',
            field=models.CharField(choices=[('personal', 'Personal details'), ('invitation', 'Invitation'), ('action', 'Action list'), ('protocol', 'Protocol'), ('synopsis', 'Synopsis'), ('guidance', 'Guidance'), ('custom', 'Custom section')], default='custom', help_text='Choose where this column should appear in the advisory board table.', max_length=20),
        ),
    ]
