# Generated by Django 5.2.6 on 2026-05-18 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0098_remove_legacy_guidance_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynopsisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='synopsis_feedback_uploads/')),
                ('synopsis_document_name', models.CharField(blank=True, max_length=255)),
                ('synopsis_document_last_updated', models.DateTimeField(blank=True, null=True)),
                ('feedback_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synopsis_feedback', to='synopsis.advisoryboardinvitation')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synopsis_feedback', to='synopsis.advisoryboardmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synopsis_feedback', to='synopsis.project')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
    ]
