# Generated by Django 5.2.6 on 2026-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0099_synopsisfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryreference',
            name='reference_folder',
            field=models.JSONField(blank=True, default=list, help_text='Shared CE subject categories assigned to this reference across the library.'),
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='reference_folder',
            new_name='unlinked_reference_folder',
        ),
        migrations.AlterField(
            model_name='reference',
            name='unlinked_reference_folder',
            field=models.JSONField(blank=True, default=list, help_text='Fallback CE subject categories used only when this project reference is not linked to the shared reference library.'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('author', 'Author'), ('advisory_board', 'Advisory Board Member'), ('external_collaborator', 'External Author')], max_length=30),
        ),
    ]
