# Generated by Codex on 2026-06-30

from django.db import migrations


APPROVED_ACTION_ROWS = [
    (
        "1.1",
        "Land/water protection - 1.1 Site/area protection",
        10,
        ["Land/water protection-Area protection"],
    ),
    (
        "1.2",
        "Land/water protection - 1.2 Resource & habitat protection",
        20,
        ["Land/water protection-Site/area stewardship"],
    ),
    (
        "2.1",
        "Land/water management - 2.1 Site/area management",
        30,
        ["Land/water management-Site/area management"],
    ),
    (
        "2.2",
        "Land/water management - 2.2 Invasive/problematic species control",
        40,
        ["Land/water management-Invasive/problematic species control"],
    ),
    (
        "2.3",
        "Land/water management - 2.3 Habitat & natural process restoration",
        50,
        ["Land/water management-Habitat & natural process restoration"],
    ),
    (
        "3.1.1",
        "Species management - 3.1 Species management - 3.1.1 Harvest management",
        60,
        [],
    ),
    (
        "3.1.2",
        "Species management - 3.1 Species management - 3.1.2 Trade management",
        70,
        [],
    ),
    (
        "3.1.3",
        "Species management - 3.1 Species management - 3.1.3 Limiting population growth",
        80,
        [],
    ),
    (
        "3.2",
        "Species management - 3.2 Species recovery",
        90,
        ["Species management-Species recovery"],
    ),
    (
        "3.3.1",
        "Species management - 3.3 Species re-introduction - 3.3.1 Reintroduction",
        100,
        [],
    ),
    (
        "3.3.1",
        "Species management - 3.3 Species re-introduction - 3.3.1 Re-introduction",
        110,
        [],
    ),
    (
        "3.3.2",
        "Species management - 3.3 Species re-introduction - 3.3.2 Benign introduction",
        120,
        [],
    ),
    (
        "3.4.1",
        "Species management - 3.4 Ex-situ conservation - 3.4.1 Captive breeding/artificial propagation",
        130,
        [],
    ),
    (
        "3.4.2",
        "Species management - 3.4 Ex-situ conservation - 3.4.2 Genome resource bank",
        140,
        [],
    ),
    (
        "4.1",
        "Education & awareness - 4.1 Formal education",
        150,
        ["Education & awareness-Formal education"],
    ),
    (
        "4.2",
        "Education & awareness - 4.2 Training",
        160,
        ["Education & awareness-Training"],
    ),
    (
        "4.3",
        "Education & awareness - 4.3 Awareness & communications",
        170,
        ["Education & awareness-Awareness & communications"],
    ),
    (
        "5.1.1",
        "Law & policy - 5.1 Legislation - 5.1.1 International level",
        180,
        [],
    ),
    (
        "5.1.2",
        "Law & policy - 5.1 Legislation - 5.1.2 National level",
        190,
        [],
    ),
    (
        "5.1.3",
        "Law & policy - 5.1 Legislation - 5.1.3 Sub-national level",
        200,
        [],
    ),
    (
        "5.1.4",
        "Law & policy - 5.1 Legislation - 5.1.4 Scale unspecified",
        210,
        [],
    ),
    (
        "5.2",
        "Law & policy - 5.2 Policies and regulations",
        220,
        [
            "Law & policy-Policies & regulations",
            "Law & policy-Regulations",
        ],
    ),
    (
        "5.3",
        "Law & policy - 5.3 Private sector standards & codes",
        230,
        ["Law & policy-Private sector standards & codes"],
    ),
    (
        "5.4.1",
        "Law & policy - 5.4 Compliance and enforcement - 5.4.1 International level",
        240,
        [],
    ),
    (
        "5.4.3",
        "Law & policy - 5.4 Compliance and enforcement - 5.4.3 Sub-national level",
        250,
        [],
    ),
    (
        "5.4.4",
        "Law & policy - 5.4 Compliance and enforcement - 5.4.4 Scale unspecified",
        260,
        [],
    ),
    (
        "6.1",
        "Livelihood, economic & other incentives - 6.1 Linked enterprises & livelihood alternatives",
        270,
        [
            "Livelihood, economic & other incentives-Linked enterprises & livelihood alternatives"
        ],
    ),
    (
        "6.2",
        "Livelihood, economic & other incentives - 6.2 Substitution",
        280,
        [],
    ),
    (
        "6.3",
        "Livelihood, economic & other incentives - 6.3 Market forces",
        290,
        ["Livelihood, economic & other incentives-Market forces"],
    ),
    (
        "6.4",
        "Livelihood, economic & other incentives - 6.4 Conservation payments",
        300,
        ["Livelihood, economic & other incentives-Conservation payments"],
    ),
    (
        "6.5",
        "Livelihood, economic & other incentives - 6.5 Non-monetary values",
        310,
        ["Livelihood, economic & other incentives-Non-monetary values"],
    ),
]

LEGACY_DETAILED_ACTION_ROWS = [
    ("1.1", "Land/water protection-Area protection", 10),
    ("1.2", "Land/water protection-Site/area stewardship", 20),
    ("2.1", "Land/water management-Site/area management", 30),
    ("2.2", "Land/water management-Invasive/problematic species control", 40),
    ("2.3", "Land/water management-Habitat & natural process restoration", 50),
    ("2.4", "Land/water management-Natural process regeneration", 60),
    ("3.1", "Species management-Species recovery", 70),
    ("3.2", "Species management-Species re-introduction", 80),
    ("3.3", "Species management-Ex situ conservation", 90),
    ("3.4", "Species management-Conservation translocation", 100),
    ("3.5", "Species management-Disease/pathogen treatment", 110),
    ("3.6", "Species management-Biological resource use management", 120),
    ("4.1", "Education & awareness-Formal education", 130),
    ("4.2", "Education & awareness-Training", 140),
    ("4.3", "Education & awareness-Awareness & communications", 150),
    ("5.1", "Law & policy-Legislation", 160),
    ("5.2", "Law & policy-Regulations", 170),
    ("5.3", "Law & policy-Incentives", 180),
    ("5.4", "Law & policy-Private sector standards & codes", 190),
    ("5.5", "Law & policy-Policies & regulations", 200),
    ("5.6", "Law & policy-Law enforcement & prosecution", 210),
    (
        "6.1",
        "Livelihood, economic & other incentives-Linked enterprises & livelihood alternatives",
        220,
    ),
    ("6.2", "Livelihood, economic & other incentives-Incentives/subsidies", 230),
    ("6.3", "Livelihood, economic & other incentives-Market forces", 240),
    ("6.4", "Livelihood, economic & other incentives-Conservation payments", 250),
    ("6.5", "Livelihood, economic & other incentives-Non-monetary values", 260),
    ("7.1", "External capacity building-Institutional development", 270),
    ("7.2", "External capacity building-Alliance & partnership development", 280),
    ("7.3", "External capacity building-Conservation finance", 290),
    ("7.4", "External capacity building-Capacity building", 300),
    ("7.5", "External capacity building-Technology transfer", 310),
    ("8.1", "Research & monitoring-Basic research & status monitoring", 320),
    ("8.2", "Research & monitoring-Resource & habitat management", 330),
    ("8.3", "Research & monitoring-Species management", 340),
    ("8.4", "Research & monitoring-Socio-economics", 350),
    ("8.5", "Research & monitoring-Conservation planning", 360),
    ("8.6", "Research & monitoring-Other", 370),
]

BROAD_ACTION_ROWS = [
    ("1", "Land/water protection", 10),
    ("2", "Land/water management", 20),
    ("3", "Species management", 30),
    ("4", "Education & awareness", 40),
    ("5", "Law & policy", 50),
    ("6", "Livelihood/economic incentives", 60),
    ("7", "External capacity building", 70),
]

APPROVED_TO_LEGACY_ACTION_NAME = {
    "Land/water protection - 1.1 Site/area protection": "Land/water protection-Area protection",
    "Land/water protection - 1.2 Resource & habitat protection": "Land/water protection-Site/area stewardship",
    "Land/water management - 2.1 Site/area management": "Land/water management-Site/area management",
    "Land/water management - 2.2 Invasive/problematic species control": "Land/water management-Invasive/problematic species control",
    "Land/water management - 2.3 Habitat & natural process restoration": "Land/water management-Habitat & natural process restoration",
    "Species management - 3.1 Species management - 3.1.1 Harvest management": "Species management-Biological resource use management",
    "Species management - 3.1 Species management - 3.1.2 Trade management": "Species management-Biological resource use management",
    "Species management - 3.1 Species management - 3.1.3 Limiting population growth": "Species management-Biological resource use management",
    "Species management - 3.2 Species recovery": "Species management-Species recovery",
    "Species management - 3.3 Species re-introduction - 3.3.1 Reintroduction": "Species management-Species re-introduction",
    "Species management - 3.3 Species re-introduction - 3.3.1 Re-introduction": "Species management-Species re-introduction",
    "Species management - 3.3 Species re-introduction - 3.3.2 Benign introduction": "Species management-Species re-introduction",
    "Species management - 3.4 Ex-situ conservation - 3.4.1 Captive breeding/artificial propagation": "Species management-Ex situ conservation",
    "Species management - 3.4 Ex-situ conservation - 3.4.2 Genome resource bank": "Species management-Ex situ conservation",
    "Education & awareness - 4.1 Formal education": "Education & awareness-Formal education",
    "Education & awareness - 4.2 Training": "Education & awareness-Training",
    "Education & awareness - 4.3 Awareness & communications": "Education & awareness-Awareness & communications",
    "Law & policy - 5.1 Legislation - 5.1.1 International level": "Law & policy-Legislation",
    "Law & policy - 5.1 Legislation - 5.1.2 National level": "Law & policy-Legislation",
    "Law & policy - 5.1 Legislation - 5.1.3 Sub-national level": "Law & policy-Legislation",
    "Law & policy - 5.1 Legislation - 5.1.4 Scale unspecified": "Law & policy-Legislation",
    "Law & policy - 5.2 Policies and regulations": "Law & policy-Policies & regulations",
    "Law & policy - 5.3 Private sector standards & codes": "Law & policy-Private sector standards & codes",
    "Law & policy - 5.4 Compliance and enforcement - 5.4.1 International level": "Law & policy-Law enforcement & prosecution",
    "Law & policy - 5.4 Compliance and enforcement - 5.4.3 Sub-national level": "Law & policy-Law enforcement & prosecution",
    "Law & policy - 5.4 Compliance and enforcement - 5.4.4 Scale unspecified": "Law & policy-Law enforcement & prosecution",
    "Livelihood, economic & other incentives - 6.1 Linked enterprises & livelihood alternatives": "Livelihood, economic & other incentives-Linked enterprises & livelihood alternatives",
    "Livelihood, economic & other incentives - 6.2 Substitution": "Livelihood, economic & other incentives-Incentives/subsidies",
    "Livelihood, economic & other incentives - 6.3 Market forces": "Livelihood, economic & other incentives-Market forces",
    "Livelihood, economic & other incentives - 6.4 Conservation payments": "Livelihood, economic & other incentives-Conservation payments",
    "Livelihood, economic & other incentives - 6.5 Non-monetary values": "Livelihood, economic & other incentives-Non-monetary values",
}


def _move_intervention_links(through_model, old_category_id, new_category_id):
    if old_category_id == new_category_id:
        return
    links = list(
        through_model.objects.filter(iucncategory_id=old_category_id).values_list(
            "synopsisintervention_id", flat=True
        )
    )
    if links:
        through_model.objects.bulk_create(
            [
                through_model(
                    synopsisintervention_id=intervention_id,
                    iucncategory_id=new_category_id,
                )
                for intervention_id in links
            ],
            ignore_conflicts=True,
            batch_size=500,
        )
    through_model.objects.filter(iucncategory_id=old_category_id).delete()


def _legacy_categories_for_names(iucn_category_model, legacy_names):
    categories = []
    seen_ids = set()
    for legacy_name in legacy_names:
        category = (
            iucn_category_model.objects.filter(kind="action", name=legacy_name)
            .order_by("id")
            .first()
        )
        if category and category.id not in seen_ids:
            categories.append(category)
            seen_ids.add(category.id)
    return categories


def _upsert_approved_action(iucn_category_model, through_model, row):
    code, name, position, legacy_names = row
    target = (
        iucn_category_model.objects.filter(kind="action", name=name)
        .order_by("id")
        .first()
    )
    legacy_categories = _legacy_categories_for_names(iucn_category_model, legacy_names)

    if target is None and legacy_categories:
        target = legacy_categories.pop(0)
        target.name = name
    elif target is None:
        target = iucn_category_model(kind="action", name=name)

    target.code = code
    target.position = position
    target.is_active = True
    target.save()

    for legacy_category in legacy_categories:
        _move_intervention_links(through_model, legacy_category.id, target.id)
        if legacy_category.is_active:
            legacy_category.is_active = False
            legacy_category.save(update_fields=["is_active"])


def forwards(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")
    SynopsisIntervention = apps.get_model("synopsis", "SynopsisIntervention")
    ThroughModel = SynopsisIntervention.iucn_actions.through

    for row in APPROVED_ACTION_ROWS:
        _upsert_approved_action(IUCNCategory, ThroughModel, row)

    approved_names = [name for _code, name, _position, _legacy_names in APPROVED_ACTION_ROWS]
    IUCNCategory.objects.filter(kind="action").exclude(name__in=approved_names).update(
        is_active=False
    )


def backwards(apps, schema_editor):
    IUCNCategory = apps.get_model("synopsis", "IUCNCategory")
    SynopsisIntervention = apps.get_model("synopsis", "SynopsisIntervention")
    ThroughModel = SynopsisIntervention.iucn_actions.through

    legacy_names = []
    for code, name, position in LEGACY_DETAILED_ACTION_ROWS:
        IUCNCategory.objects.update_or_create(
            kind="action",
            name=name,
            defaults={
                "code": code,
                "position": position,
                "is_active": True,
            },
        )
        legacy_names.append(name)

    broad_names = []
    for code, name, position in BROAD_ACTION_ROWS:
        IUCNCategory.objects.update_or_create(
            kind="action",
            name=name,
            defaults={
                "code": code,
                "position": position,
                "is_active": False,
            },
        )
        broad_names.append(name)

    for approved_name, legacy_name in APPROVED_TO_LEGACY_ACTION_NAME.items():
        approved_category = (
            IUCNCategory.objects.filter(kind="action", name=approved_name)
            .order_by("id")
            .first()
        )
        legacy_category = (
            IUCNCategory.objects.filter(kind="action", name=legacy_name)
            .order_by("id")
            .first()
        )
        if approved_category and legacy_category:
            _move_intervention_links(ThroughModel, approved_category.id, legacy_category.id)

    allowed_names = set(legacy_names + broad_names)
    IUCNCategory.objects.filter(kind="action").exclude(name__in=allowed_names).update(
        is_active=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0108_expand_document_file_path_lengths"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
