# Generated by Django 5.2.6 on 2026-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synopsis", "0109_update_iucn_action_categories_to_approved_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synopsischapter",
            name="chapter_type",
            field=models.CharField(
                choices=[
                    ("text", "Narrative chapter"),
                    ("evidence", "Evidence chapter"),
                    ("appendix", "Appendix / back matter"),
                ],
                default="evidence",
                max_length=20,
            ),
        ),
    ]
